### ISSUE TITLE
Time zone

### ISSUE THREAD

**Issue by johenrik** [enonic/app-cronjob#1]
The jobs.xml file seems to be basing itself on the server timezone. This is not always good when server is in GMT but we want things to run at a specific time regardless of summer time or normal time in my time zone. My feature request is to be able to specify the requested time zone in the jobs.xml file and that the app handles this properly.

**Comment by sigdestad** [comment]
Wow.. Jo Henrik. This has been overseen by us.
Why not implement this and send us a pull request?
