### ISSUE TITLE
Upgrade app-cronjob to be xp 7.0 compatible

### ISSUE THREAD

**Issue by ashklianko** [enonic/app-cronjob#5]
http://wiki.enonic.com/display/dev/7.0+app+upgrade+guide

**Comment by alansemenov** [comment]
@ashklianko See if you can upgrade cronjob java libs as well.

**Comment by alansemenov** [comment]
The app is upgraded but we won't release a new version until it's [switched to lib-cron](https://github.com/enonic/app-cronjob/issues/7)
